//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captain.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Captain.Application.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution type.
        /// </summary>
        public static string AboutWindow_DistributionType {
            get {
                return ResourceManager.GetString("AboutWindow_DistributionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying updates.
        /// </summary>
        public static string AboutWindow_UpdateStatusApplying {
            get {
                return ResourceManager.GetString("AboutWindow_UpdateStatusApplying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        public static string AboutWindow_UpdateStatusChecking {
            get {
                return ResourceManager.GetString("AboutWindow_UpdateStatusChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading updates.
        /// </summary>
        public static string AboutWindow_UpdateStatusDownloading {
            get {
                return ResourceManager.GetString("AboutWindow_UpdateStatusDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart {0} to complete the update.
        /// </summary>
        public static string AboutWindow_UpdateStatusReadyToRestart {
            get {
                return ResourceManager.GetString("AboutWindow_UpdateStatusReadyToRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://git.io/captain.
        /// </summary>
        public static string AboutWindow_URI {
            get {
                return ResourceManager.GetString("AboutWindow_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some tasks failed.
        /// </summary>
        public static string ActionErrorDialog_PartialFailureCaption {
            get {
                return ResourceManager.GetString("ActionErrorDialog_PartialFailureCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all output streams could process your capture. Refer to the application log for technical information..
        /// </summary>
        public static string ActionErrorDialog_PartialFailureContent {
            get {
                return ResourceManager.GetString("ActionErrorDialog_PartialFailureContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AeroIndicatorStrip {
            get {
                object obj = ResourceManager.GetObject("AeroIndicatorStrip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About….
        /// </summary>
        public static string AppMenu_About {
            get {
                return ResourceManager.GetString("AppMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        public static string AppMenu_Exit {
            get {
                return ResourceManager.GetString("AppMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options….
        /// </summary>
        public static string AppMenu_Options {
            get {
                return ResourceManager.GetString("AppMenu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon AppxIcon {
            get {
                object obj = ResourceManager.GetObject("AppxIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CopyToClipboard {
            get {
                object obj = ResourceManager.GetObject("CopyToClipboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EncoderOptions {
            get {
                object obj = ResourceManager.GetObject("EncoderOptions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FluentIndicatorStrip {
            get {
                object obj = ResourceManager.GetObject("FluentIndicatorStrip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide error &amp;details.
        /// </summary>
        public static string GenericActionErrorDialog_HideDetails {
            get {
                return ResourceManager.GetString("GenericActionErrorDialog_HideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show error &amp;details.
        /// </summary>
        public static string GenericActionErrorDialog_ShowDetails {
            get {
                return ResourceManager.GetString("GenericActionErrorDialog_ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring the application will delete all plugins, logs and customizations. We won&apos;t touch your captures..
        /// </summary>
        public static string OptionsWindow_RestoreDialogContent {
            get {
                return ResourceManager.GetString("OptionsWindow_RestoreDialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset everything.
        /// </summary>
        public static string OptionsWindow_RestoreDialogHardButton {
            get {
                return ResourceManager.GetString("OptionsWindow_RestoreDialogHardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string OptionsWindow_RestoreDialogInstruction {
            get {
                return ResourceManager.GetString("OptionsWindow_RestoreDialogInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore options only.
        /// </summary>
        public static string OptionsWindow_RestoreDialogOptionsButton {
            get {
                return ResourceManager.GetString("OptionsWindow_RestoreDialogOptionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are not the droids you are looking for. Move along!.
        /// </summary>
        public static string OutputStreamSelectionDialog_EmptyMarkup {
            get {
                return ResourceManager.GetString("OutputStreamSelectionDialog_EmptyMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Placeholder {
            get {
                object obj = ResourceManager.GetObject("Placeholder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown publisher.
        /// </summary>
        public static string Plugin_DefaultPublisherName {
            get {
                return ResourceManager.GetString("Plugin_DefaultPublisherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration interface for this plugin cannot be displayed.
        ///Contact the plugin vendor for further information..
        /// </summary>
        public static string PluginManager_EncoderConfigurationUIError {
            get {
                return ResourceManager.GetString("PluginManager_EncoderConfigurationUIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SaveToFile {
            get {
                object obj = ResourceManager.GetObject("SaveToFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SnackBarClose {
            get {
                object obj = ResourceManager.GetObject("SnackBarClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SnackBarMute {
            get {
                object obj = ResourceManager.GetObject("SnackBarMute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SnackBarOptions {
            get {
                object obj = ResourceManager.GetObject("SnackBarOptions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SnackBarRecord {
            get {
                object obj = ResourceManager.GetObject("SnackBarRecord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SnackBarScreenshot {
            get {
                object obj = ResourceManager.GetObject("SnackBarScreenshot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SnackBarStop {
            get {
                object obj = ResourceManager.GetObject("SnackBarStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SnackBarUnmute {
            get {
                object obj = ResourceManager.GetObject("SnackBarUnmute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not capture the screen due to an internal error.
        ///Tap here to see details..
        /// </summary>
        public static string Task_CaptureFailedBody {
            get {
                return ResourceManager.GetString("Task_CaptureFailedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture failed.
        /// </summary>
        public static string Task_CaptureFailedCaption {
            get {
                return ResourceManager.GetString("Task_CaptureFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required encoder may have not been properly initialized, there were no actions to take or an error occurred while trying to duplicate the desktop..
        /// </summary>
        public static string Task_CaptureFailedExtendedBody {
            get {
                return ResourceManager.GetString("Task_CaptureFailedExtendedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not capture the screen.
        /// </summary>
        public static string Task_CaptureFailedExtendedCaption {
            get {
                return ResourceManager.GetString("Task_CaptureFailedExtendedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all actions could process your capture..
        /// </summary>
        public static string Task_PartialSuccessBody {
            get {
                return ResourceManager.GetString("Task_PartialSuccessBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some actions failed.
        /// </summary>
        public static string Task_PartialSuccessCaption {
            get {
                return ResourceManager.GetString("Task_PartialSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All actions succeeded..
        /// </summary>
        public static string Task_SuccessBody {
            get {
                return ResourceManager.GetString("Task_SuccessBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot taken!.
        /// </summary>
        public static string Task_SuccessCaption {
            get {
                return ResourceManager.GetString("Task_SuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TaskAdd {
            get {
                object obj = ResourceManager.GetObject("TaskAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TaskDelete {
            get {
                object obj = ResourceManager.GetObject("TaskDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TaskEdit {
            get {
                object obj = ResourceManager.GetObject("TaskEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} actions.
        /// </summary>
        public static string TaskPropertiesDialog_MultipleActions {
            get {
                return ResourceManager.GetString("TaskPropertiesDialog_MultipleActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No actions.
        /// </summary>
        public static string TaskPropertiesDialog_NoActions {
            get {
                return ResourceManager.GetString("TaskPropertiesDialog_NoActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 action.
        /// </summary>
        public static string TaskPropertiesDialog_SingleAction {
            get {
                return ResourceManager.GetString("TaskPropertiesDialog_SingleAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TaskRegionFixed {
            get {
                object obj = ResourceManager.GetObject("TaskRegionFixed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TaskRegionFullScreen {
            get {
                object obj = ResourceManager.GetObject("TaskRegionFullScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TaskRegionGrab {
            get {
                object obj = ResourceManager.GetObject("TaskRegionGrab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TaskTypeRecording {
            get {
                object obj = ResourceManager.GetObject("TaskTypeRecording", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TaskTypeScreenshot {
            get {
                object obj = ResourceManager.GetObject("TaskTypeScreenshot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon UpdateIcon {
            get {
                object obj = ResourceManager.GetObject("UpdateIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0}.
        /// </summary>
        public static string UpdaterUI_DialogCaption {
            get {
                return ResourceManager.GetString("UpdaterUI_DialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing update….
        /// </summary>
        public static string UpdaterUI_DialogInstallProgressText {
            get {
                return ResourceManager.GetString("UpdaterUI_DialogInstallProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update….
        /// </summary>
        public static string UpdaterUI_DialogProgressText {
            get {
                return ResourceManager.GetString("UpdaterUI_DialogProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of {0} ({1}) is available—yours is {2}.
        ///Would you like to install it?.
        /// </summary>
        public static string UpdaterUI_DialogText {
            get {
                return ResourceManager.GetString("UpdaterUI_DialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remind me later.
        /// </summary>
        public static string UpdaterUI_RemindLaterButton {
            get {
                return ResourceManager.GetString("UpdaterUI_RemindLaterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Update.
        /// </summary>
        public static string UpdaterUI_UpdateButton {
            get {
                return ResourceManager.GetString("UpdaterUI_UpdateButton", resourceCulture);
            }
        }
    }
}
