//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captain.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Captain.Application.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ActionOptions {
            get {
                object obj = ResourceManager.GetObject("ActionOptions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AddInOptions {
            get {
                object obj = ResourceManager.GetObject("AddInOptions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About….
        /// </summary>
        public static string AppMenu_About {
            get {
                return ResourceManager.GetString("AppMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Capture.
        /// </summary>
        public static string AppMenu_Capture {
            get {
                return ResourceManager.GetString("AppMenu_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        public static string AppMenu_Exit {
            get {
                return ResourceManager.GetString("AppMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options….
        /// </summary>
        public static string AppMenu_Options {
            get {
                return ResourceManager.GetString("AppMenu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BasicOptions {
            get {
                object obj = ResourceManager.GetObject("BasicOptions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captures.
        /// </summary>
        public static string CapturesFolderName {
            get {
                return ResourceManager.GetString("CapturesFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide error &amp;details.
        /// </summary>
        public static string GenericActionErrorDialog_HideDetails {
            get {
                return ResourceManager.GetString("GenericActionErrorDialog_HideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show error &amp;details.
        /// </summary>
        public static string GenericActionErrorDialog_ShowDetails {
            get {
                return ResourceManager.GetString("GenericActionErrorDialog_ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GrabberUI_Cancel {
            get {
                return ResourceManager.GetString("GrabberUI_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture!.
        /// </summary>
        public static string GrabberUI_Capture {
            get {
                return ResourceManager.GetString("GrabberUI_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse.
        /// </summary>
        public static string GrabberUI_EllipseTool {
            get {
                return ResourceManager.GetString("GrabberUI_EllipseTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string GrabberUI_LineTool {
            get {
                return ResourceManager.GetString("GrabberUI_LineTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string GrabberUI_Record {
            get {
                return ResourceManager.GetString("GrabberUI_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string GrabberUI_RectangleTool {
            get {
                return ResourceManager.GetString("GrabberUI_RectangleTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop recording.
        /// </summary>
        public static string GrabberUI_StopRecording {
            get {
                return ResourceManager.GetString("GrabberUI_StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle.
        /// </summary>
        public static string GrabberUI_TriangleTool {
            get {
                return ResourceManager.GetString("GrabberUI_TriangleTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string GrabberUI_TypeTool {
            get {
                return ResourceManager.GetString("GrabberUI_TypeTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string GrabberUI_Undo {
            get {
                return ResourceManager.GetString("GrabberUI_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture failed.
        /// </summary>
        public static string Toast_CaptureFailedCaption {
            get {
                return ResourceManager.GetString("Toast_CaptureFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either the capture failed or there was a media encoding problem..
        /// </summary>
        public static string Toast_CaptureFailedContent {
            get {
                return ResourceManager.GetString("Toast_CaptureFailedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The capture could not be processed.
        /// </summary>
        public static string Toast_HandlerFailedCaption {
            get {
                return ResourceManager.GetString("Toast_HandlerFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while handling this capture.
        /// </summary>
        public static string Toast_HandlerFailedContent {
            get {
                return ResourceManager.GetString("Toast_HandlerFailedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save capture.
        /// </summary>
        public static string Toast_LocalSaveFailedCaption {
            get {
                return ResourceManager.GetString("Toast_LocalSaveFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to save this capture..
        /// </summary>
        public static string Toast_LocalSaveFailedContent {
            get {
                return ResourceManager.GetString("Toast_LocalSaveFailedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A local copy of this capture could not be saved..
        /// </summary>
        public static string Toast_LocalSaveFailedSubText {
            get {
                return ResourceManager.GetString("Toast_LocalSaveFailedSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Toast_Open {
            get {
                return ResourceManager.GetString("Toast_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in folder.
        /// </summary>
        public static string Toast_ViewInFolder {
            get {
                return ResourceManager.GetString("Toast_ViewInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TrayIconStrip {
            get {
                object obj = ResourceManager.GetObject("TrayIconStrip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UpdateOptions {
            get {
                object obj = ResourceManager.GetObject("UpdateOptions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
